services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: wildcard_user
      POSTGRES_PASSWORD: wildcard_password
      POSTGRES_DB: wildcard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
