[tox]
envlist = py312,py313,py314,py315
isolated_build = True

[testenv]
passenv =
    PIP_NO_BINARY
    HYPOTHESIS_NO_EXTENSION
deps =
    pytest
    pytest-asyncio
    hypothesis
commands =
    pytest {posargs:tests/}
