"""Rename Prompt to Mission.

Revision ID: 7611442310ec
Revises: f6093771bac3
Create Date: 2026-04-25 00:48:26.287494

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7611442310ec"
down_revision: Union[str, Sequence[str], None] = "f6093771bac3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Mission",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "BatchMission",
        sa.Column("batch_id", sa.String(), nullable=False),
        sa.Column("mission_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["Batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["Mission.id"],
        ),
        sa.PrimaryKeyConstraint("batch_id", "mission_id"),
    )
    op.drop_table("BatchPrompt")
    op.drop_table("Prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Prompt",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("text", sa.VARCHAR(), nullable=False),
        sa.Column("category", sa.VARCHAR(), nullable=False),
        sa.Column("difficulty", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "BatchPrompt",
        sa.Column("batch_id", sa.VARCHAR(), nullable=False),
        sa.Column("prompt_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["Batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["Prompt.id"],
        ),
        sa.PrimaryKeyConstraint("batch_id", "prompt_id"),
    )
    op.drop_table("BatchMission")
    op.drop_table("Mission")
    # ### end Alembic commands ###
